# Generated by Django 3.2.16 on 2023-02-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localization',
            name='line2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
