# Generated by Django 3.2.16 on 2023-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('comments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_places',
            name='assessments',
            field=models.ManyToManyField(to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='tourist_places',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
