# Generated by Django 3.2.16 on 2023-01-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('core', '0002_auto_20230128_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_places',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.localization'),
            preserve_default=False,
        ),
    ]
