# Generated by Django 3.2.16 on 2023-02-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_alter_localization_line2'),
        ('core', '0003_tourist_places_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist_places',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.localization'),
        ),
    ]
