# Generated by Django 3.2.16 on 2023-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tourist_places_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_places',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_places'),
        ),
    ]
