# Generated by Django 3.2.16 on 2023-02-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tourist_places_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tourist_places',
            name='identification_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.identificationdoc'),
        ),
    ]
